name: Docker build 
on: # 
  workflow_dispatch: 
    inputs: 
      tag:
        description: 'Docker image tag' 
        required: true 
jobs: 
  build: 
    runs-on: ubuntu-latest 
  
    steps:
    - name: Checkout code 
      uses: actions/checkout@v2 
      
    - name: check env
      run: echo "${{ env.DOCKER_USERNAME }}"
    
    - name: Build Docker image 
      run: docker build -t nastyavolskaya/my-image-name:${{ github.event.inputs.tag }} . 

    - name: Push Docker image to Docker hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ env.DOCKER_USERNAME }} --password-stdin
        docker push nastyavolskaya/my-image-name:${{ github.event.inputs.tag }}
