name: Docker build # Название workflow
on: # На что будет триггерится workflow
  workflow_dispatch: # Установливаем ручной запуск workflow
    inputs: # Ручной запуск будет включать показ окошка с указанием тега
      tag: # Название входного параметра 
        description: 'Docker image tag' # Задаем описание тега, который будет указан в названии всплывающего окошка.
        required: true # Указываем, что в всплывающем окошке обязательно нужно ввести тег. 
jobs: 
  build: # Название джобы
    runs-on: ubuntu-latest # Указываем где она будет запускаться

    steps:
    - name: Checkout code # Название шага, который будет выполнять джоба. В данном случае получение кода из репозитория.
      uses: actions/checkout@v2 # Здесь используем actions из гитхаба, это кусок уже написанного кода от разработчиков гитхаба.

    - name: Build Docker image 
      run: docker build -t nastyavolskaya/my-image-name:${{ github.event.inputs.tag }} . # Билдим проект, и в конце автоматически подставляется тег, который мы указали в плашке через expresions

    - name: Push Docker image to Docker hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ env.DOCKER_USERNAME }} --password-stdin
        docker push nastyavolskaya/my-image-name:${{ github.event.inputs.tag }}
