name: Test workflow # Название workflow
on: workflow_dispatch # На какой триггер будет реагировать workflow, чтобы автоматически запуститься. workflow_dispatch означает, что он будет запускаться в ручном режиме.
jobs:
  print_test: #Даем название джобе, которая будет отражать, то чем она будет заниматься.
    runs-on: ubuntu-latest #Указываем на какой машине, на каком сервере, с какой операционной системой необходимо запустить данный workflow
    steps: #Шаг, который будет выполнять джоба
      - name: Print to console # Даем название шагу, который будет выполняться
        run: echo Hello GH actions #Запускаем команду, которая у нас будет выполнена на данном шаге.
      - name: Print to lines # Внутри одной джобы может быть сколько угодно шагов, это второй шаг с выводом нескольких линей в консоль.
        run: |
          echo First line
          echo Second line
